FROM esycat/java:oracle-8

MAINTAINER "Eugene Janusov" <esycat@gmail.com>

ENV YOUTRACK_BUILD 6.0.12619
ENV YOUTRACK_PORT 8080
ENV YOUTRACK_USER youtrack
ENV YOUTRACK_SUFFIX youtrack

ENV YOUTRACK_DISTFILE youtrack-${YOUTRACK_BUILD}.jar
ENV YOUTRACK_PREFIX /opt
ENV YOUTRACK_DIR $YOUTRACK_PREFIX/$YOUTRACK_SUFFIX
ENV YOUTRACK_HOME /var/lib/$YOUTRACK_SUFFIX

RUN mkdir $YOUTRACK_DIR
WORKDIR $YOUTRACK_DIR
ADD https://download.jetbrains.com/charisma/$YOUTRACK_DISTFILE $YOUTRACK_DIR/
# COPY $YOUTRACK_DISTFILE $YOUTRACK_DIR/
RUN chmod +r $YOUTRACK_DISTFILE
RUN ln -s $YOUTRACK_DISTFILE youtrack.jar

RUN mkdir $YOUTRACK_HOME
RUN groupadd -r $YOUTRACK_USER
RUN useradd -r -g $YOUTRACK_USER -d $YOUTRACK_HOME $YOUTRACK_USER
RUN chown -R $YOUTRACK_USER:$YOUTRACK_USER $YOUTRACK_HOME

USER $YOUTRACK_USER
CMD ["java", "-Xmx1g", "-Djava.awt.headless=true", "-jar", "youtrack.jar", "$YOUTRACK_PORT"]
EXPOSE $YOUTRACK_PORT
VOLUME ["$YOUTRACK_HOME"]
